# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e049dc736e69faf2fa560ad2b6c5c5f1cbe68a2e664baf42b73bd103a470284ed9aad10639339f86ccaa3aa8dc39d658af246e3fb68015d831fd9ae3dc4c8137

test:
  secret_key_base: 725cd65731705081c72b1a71f1ef2b083f81757405053b6bc580d9eaeba2e028226755a8f42e66bd6820bd30d3e88abb331fe9b7dae2c400f157fa65cc9ec2ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
